### ISSUE TITLE
feat: integrate SDE into the umbrella chart

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/tractus-x-umbrella#100]
### Description

Simple Data Exchanger should be added to the chart with the version that was part of [24.05 release](https://github.com/eclipse-tractusx/tractus-x-release/releases/tag/24.05).

chart version: [0.1.9](https://github.com/eclipse-tractusx/managed-simple-data-exchanger/releases/tag/sde-0.1.9)

### Acceptance Criteria

- [ ] [sde chart configuration is added]
- [ ] [sde chart is added to the Chart.yaml]
- [ ] [all workflow pass]
- [ ] chart can start up locally

**Comment by almadigabor** [comment]
Hey @adityagajbhiye9, can you help us our here?

**Comment by adityagajbhiye9** [comment]
@almadigabor 
Chart has been added for 24.05 . charts and chart.yaml is updated.
app version 2.4.1 and chart version - 0.1.9
workflow all pass 
(https://github.com/eclipse-tractusx/managed-simple-data-exchanger/actions)

**Comment by almadigabor** [comment]
No, I meant integrating it here in the umbrella chart like all the other products [here](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/main/charts/umbrella/Chart.yaml#L34). And all the acceptance criteria are referred to this repo.

**Comment by adityagajbhiye9** [comment]
@almadigabor I have raised PR please review, approve and merge.
#102
