### ISSUE TITLE
Upgrade central umbrella products to R24.08

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/tractus-x-umbrella#128]
### Description

Upgrade products to R24.08

### Acceptance Criteria

- [x] portal --> done as part of https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/125 -> @mgarciaLKS 
- [x] #135
- [x] centralidp and sharedidp  --> WIP https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/127 -> @mgarciaLKS 
- [x] #136
- [x] #137
- [x] #138
- [x] #139
- [x] #140
- [x] Managed Identity Wallet --> out of scope, obsolete since R24.12

**Comment by matbmoser** [comment]
Will assign to arena

**Comment by evegufy** [comment]
done
