### ISSUE TITLE
feat: TLS and Ingress setup for the Umbrella chart

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/tractus-x-umbrella#58]
### Description

Based on the discussion in the last Umbrella Chart Sync a TLS and Ingress implementation is needed for the chart. The solution should be inspired by the [Portal localdev](https://github.com/eclipse-tractusx/portal/tree/main/charts/localdev) chart which has self-signed certificate set up and described. GitHub workflow steps should also be created so a similar setup could work in an automated way. I'm splitting this issue into 3 subtasks that can be found below.

### Acceptance Criteria

- [ ] Implement self-signed TLS and Ingress in the Umbrella chart
- [ ] Document the process of self-signed certificate creation for local setup
- [ ] Define GitHub workflow steps to have the TLS setup work there as well
